import type { CityOption } from '@/lib/stores/searchStore'

/* ============================================================
   城市 + 机场数据 / City + Airport data
   ============================================================ */

/** 城市主要机场映射 (无机场城市不列入) */
const CITY_PRIMARY: Record<string, string> = {
  // 中国 — 直辖市 & 省会
  '北京': 'PEK', '上海': 'PVG', '广州': 'CAN', '深圳': 'SZX',
  '成都': 'CTU', '重庆': 'CKG', '杭州': 'HGH', '西安': 'XIY',
  '南京': 'NKG', '武汉': 'WUH', '长沙': 'CSX', '昆明': 'KMG',
  '天津': 'TSN', '青岛': 'TAO', '厦门': 'XMN', '郑州': 'CGO',
  '沈阳': 'SHE', '哈尔滨': 'HRB', '大连': 'DLC', '福州': 'FOC',
  '南宁': 'NNG', '贵阳': 'KWE', '海口': 'HAK', '三亚': 'SYX',
  '乌鲁木齐': 'URC', '拉萨': 'LXA', '兰州': 'LHW', '太原': 'TYN',
  '南昌': 'KHN', '合肥': 'HFE', '石家庄': 'SJW', '济南': 'TNA',
  '长春': 'CGQ', '呼和浩特': 'HET', '银川': 'INC', '西宁': 'XNN',
  // 中国 — 热门 & 旅游城市（有机场）
  '温州': 'WNZ', '宁波': 'NGB', '无锡': 'WUX', '烟台': 'YNT',
  '珠海': 'ZUH', '桂林': 'KWL', '丽江': 'LJG', '张家界': 'DYG',
  '黄山': 'TXN', '九寨沟': 'JZH', '西双版纳': 'JHG', '神农架': 'HPG',
  '喀什': 'KHG', '敦煌': 'DNH', '澳门': 'MFM', '香港': 'HKG',
  '台北': 'TPE', '高雄': 'KHH', '花莲': 'HUN', '台南': 'TNN',
  '稻城亚丁': 'YBP', '香格里拉': 'DIG', '呼伦贝尔': 'HLD',
  '阿勒泰': 'AAT', '额济纳': 'EJN', '腾冲': 'TCZ', '芒市': 'LUM',
  '格尔木': 'GOQ', '玉树': 'YUS',
  // 中国 — 新增有机场城市
  '秦皇岛': 'BPE', '邯郸': 'HDG', '张家口': 'ZQZ',
  '大同': 'DAT', '运城': 'YCU', '长治': 'CIH', '吕梁': 'LLV',
  '包头': 'BAV', '鄂尔多斯': 'DSN', '满洲里': 'NZH', '阿尔山': 'YIE',
  '赤峰': 'CIF', '通辽': 'TGO', '锡林浩特': 'XIL', '乌兰浩特': 'HLH',
  '丹东': 'DDG', '锦州': 'JNZ', '朝阳': 'CHG', '营口': 'YKH',
  '延吉': 'YNJ', '白山': 'NBS', '白城': 'DBC', '通化': 'TNH',
  '齐齐哈尔': 'NDG', '牡丹江': 'MDG', '佳木斯': 'JMU',
  '漠河': 'OHE', '伊春': 'LDS', '黑河': 'HEK', '大庆': 'DQA', '鸡西': 'JXA',
  '常州': 'CZX', '徐州': 'XUZ', '扬州': 'YTY', '南通': 'NTG',
  '连云港': 'LYG', '盐城': 'YNZ', '淮安': 'HIA',
  '义乌': 'YIW', '舟山': 'HSN', '台州': 'HYN', '衢州': 'JUZ',
  '安庆': 'AQG', '阜阳': 'FUG', '池州': 'JUH', '芜湖': 'WHA',
  '泉州': 'JJN', '武夷山': 'WUS',
  '景德镇': 'JDZ', '赣州': 'KOW', '井冈山': 'JGS', '上饶': 'SQD', '宜春': 'YIC',
  '威海': 'WEH', '潍坊': 'WEF', '临沂': 'LYI', '济宁': 'JNG',
  '日照': 'RIZ', '东营': 'DOY',
  '洛阳': 'LYA', '南阳': 'NNY', '信阳': 'XAI',
  '宜昌': 'YIH', '襄阳': 'XFN', '恩施': 'ENH', '十堰': 'WDS',
  '衡阳': 'HNY', '常德': 'CGD', '怀化': 'HJJ', '永州': 'LLF', '邵阳': 'WGN',
  '汕头': 'SWA', '惠州': 'HUZ', '湛江': 'ZHA', '梅州': 'MXZ',
  '北海': 'BHY', '柳州': 'LZH', '百色': 'AEB', '河池': 'HCJ',
  '琼海': 'BAR',
  '绵阳': 'MIG', '泸州': 'LZO', '宜宾': 'YBP', '西昌': 'XIC',
  '康定': 'KGT', '攀枝花': 'PZI', '广元': 'GYS', '南充': 'NAO', '达州': 'DAX',
  '遵义': 'ZYI', '铜仁': 'TEN', '安顺': 'AVA', '兴义': 'ACX',
  '荔波': 'LLB', '六盘水': 'LPF', '毕节': 'BFJ',
  '大理': 'DLU', '保山': 'BSD', '文山': 'WNH', '普洱': 'SYM',
  '临沧': 'LNJ', '泸沽湖': 'NLH', '澜沧': 'JMJ',
  '林芝': 'LZY', '日喀则': 'RKZ', '阿里': 'NGQ', '昌都': 'BPX',
  '延安': 'ENY', '汉中': 'HZG', '榆林': 'UYN',
  '嘉峪关': 'JGN', '张掖': 'YZY', '天水': 'THQ', '庆阳': 'IQN', '甘南': 'GXH',
  '中卫': 'ZHY', '固原': 'GYU',
  '伊宁': 'YIN', '库尔勒': 'KRL', '和田': 'HTN', '克拉玛依': 'KRY',
  '那拉提': 'NLT', '塔城': 'TCG', '阿克苏': 'AKU', '库车': 'KCA',
  '万州': 'WXN',
  // 日本
  '东京': 'NRT', '大阪': 'KIX', '札幌': 'CTS', '福冈': 'FUK',
  '名古屋': 'NGO', '冲绳': 'OKA', '广岛': 'HIJ', '仙台': 'SDJ',
  '鹿儿岛': 'KOJ', '金泽': 'KMQ', '松山': 'MYJ',
  // 韩国
  '首尔': 'ICN', '釜山': 'PUS', '济州': 'CJU',
  // 东南亚
  '新加坡': 'SIN', '曼谷': 'BKK', '普吉': 'HKT', '清迈': 'CNX',
  '芭提雅': 'UTP', '苏梅': 'USM', '吉隆坡': 'KUL', '槟城': 'PEN',
  '亚庇': 'BKI', '古晋': 'KCH', '巴厘岛': 'DPS', '雅加达': 'CGK',
  '泗水': 'SUB', '日惹': 'JOG', '马尼拉': 'MNL', '宿务': 'CEB',
  '长滩岛': 'MPH', '胡志明市': 'SGN', '河内': 'HAN', '岘港': 'DAD',
  '芽庄': 'CXR', '富国岛': 'PQC', '金边': 'PNH', '暹粒': 'REP',
  '仰光': 'RGN', '科伦坡': 'CMB', '马尔代夫': 'MLE',
  '缅甸蒲甘': 'NYU', '老挝万象': 'VTE', '龙坡邦': 'LPQ',
  // 中东
  '迪拜': 'DXB', '阿布扎比': 'AUH', '多哈': 'DOH', '伊斯坦布尔': 'IST',
  '特拉维夫': 'TLV', '利雅得': 'RUH',
  // 欧洲
  '巴黎': 'CDG', '伦敦': 'LHR', '罗马': 'FCO', '巴塞罗那': 'BCN',
  '马德里': 'MAD', '阿姆斯特丹': 'AMS', '法兰克福': 'FRA',
  '慕尼黑': 'MUC', '维也纳': 'VIE', '苏黎世': 'ZRH', '日内瓦': 'GVA',
  '布鲁塞尔': 'BRU', '哥本哈根': 'CPH', '斯德哥尔摩': 'ARN',
  '奥斯陆': 'OSL', '赫尔辛基': 'HEL', '布拉格': 'PRG',
  '布达佩斯': 'BUD', '华沙': 'WAW', '里斯本': 'LIS', '雅典': 'ATH',
  '米兰': 'MXP', '威尼斯': 'VCE', '佛罗伦萨': 'FLR', '那不勒斯': 'NAP',
  '苏格兰爱丁堡': 'EDI', '曼彻斯特': 'MAN', '都柏林': 'DUB',
  '赖克雅未克': 'KEF',
  // 大洋洲
  '悉尼': 'SYD', '墨尔本': 'MEL', '布里斯班': 'BNE', '珀斯': 'PER',
  '奥克兰': 'AKL', '皇后镇': 'ZQN', '基督城': 'CHC',
  // 美洲
  '纽约': 'JFK', '洛杉矶': 'LAX', '旧金山': 'SFO',
  '拉斯维加斯': 'LAS', '芝加哥': 'ORD', '迈阿密': 'MIA',
  '夏威夷': 'HNL', '西雅图': 'SEA', '波士顿': 'BOS',
  '华盛顿': 'IAD', '多伦多': 'YYZ', '温哥华': 'YVR',
  '墨西哥城': 'MEX', '坎昆': 'CUN', '圣保罗': 'GRU',
  '布宜诺斯艾利斯': 'EZE', '利马': 'LIM', '波哥大': 'BOG',
  // 南亚
  '新德里': 'DEL', '孟买': 'BOM', '斋普尔': 'JAI', '加尔各答': 'CCU',
  '班加罗尔': 'BLR', '果阿': 'GOI', '卡拉奇': 'KHI',
  // 非洲
  '开罗': 'CAI', '摩洛哥马拉喀什': 'RAK', '内罗毕': 'NBO',
  '约翰内斯堡': 'JNB', '开普敦': 'CPT',
  // 俄罗斯/中亚
  '莫斯科': 'SVO', '圣彼得堡': 'LED', '阿拉木图': 'ALA',
  '塔什干': 'TAS', '撒马尔罕': 'SKD',
}

export const POPULAR_CITIES: CityOption[] = [
  // ══════════════════════════════════════════════════════════
  // 中国内地 — 直辖市
  // ══════════════════════════════════════════════════════════
  { code: 'PEK', name: '北京',      nameEn: 'Beijing',         airport: '首都国际机场',       country: '中国' },
  { code: 'PKX', name: '北京',      nameEn: 'Beijing',         airport: '大兴国际机场',       country: '中国' },
  { code: 'PVG', name: '上海',      nameEn: 'Shanghai',        airport: '浦东国际机场',       country: '中国' },
  { code: 'SHA', name: '上海',      nameEn: 'Shanghai',        airport: '虹桥国际机场',       country: '中国' },
  { code: 'TSN', name: '天津',      nameEn: 'Tianjin',         airport: '滨海国际机场',       country: '中国' },
  { code: 'CKG', name: '重庆',      nameEn: 'Chongqing',       airport: '江北国际机场',       country: '中国' },
  { code: 'WXN', name: '万州',      nameEn: 'Wanzhou',         airport: '万州五桥机场',       country: '中国' },

  // ══ 河北省 ══
  { code: 'SJW', name: '石家庄',    nameEn: 'Shijiazhuang',    airport: '正定国际机场',       country: '中国' },
  { code: '',    name: '唐山',      nameEn: 'Tangshan',        airport: '',                   country: '中国' },
  { code: 'BPE', name: '秦皇岛',    nameEn: 'Qinhuangdao',    airport: '北戴河机场',         country: '中国' },
  { code: 'HDG', name: '邯郸',      nameEn: 'Handan',          airport: '邯郸机场',           country: '中国' },
  { code: '',    name: '保定',      nameEn: 'Baoding',         airport: '',                   country: '中国' },
  { code: 'ZQZ', name: '张家口',    nameEn: 'Zhangjiakou',     airport: '张家口宁远机场',     country: '中国' },
  { code: '',    name: '承德',      nameEn: 'Chengde',         airport: '',                   country: '中国' },
  { code: '',    name: '沧州',      nameEn: 'Cangzhou',        airport: '',                   country: '中国' },
  { code: '',    name: '廊坊',      nameEn: 'Langfang',        airport: '',                   country: '中国' },
  { code: '',    name: '衡水',      nameEn: 'Hengshui',        airport: '',                   country: '中国' },
  { code: '',    name: '邢台',      nameEn: 'Xingtai',         airport: '',                   country: '中国' },

  // ══ 山西省 ══
  { code: 'TYN', name: '太原',      nameEn: 'Taiyuan',         airport: '武宿国际机场',       country: '中国' },
  { code: 'DAT', name: '大同',      nameEn: 'Datong',          airport: '云冈机场',           country: '中国' },
  { code: 'YCU', name: '运城',      nameEn: 'Yuncheng',        airport: '关公机场',           country: '中国' },
  { code: 'CIH', name: '长治',      nameEn: 'Changzhi',        airport: '王村机场',           country: '中国' },
  { code: 'LLV', name: '吕梁',      nameEn: 'Lvliang',         airport: '大武机场',           country: '中国' },
  { code: '',    name: '晋中',      nameEn: 'Jinzhong',        airport: '',                   country: '中国' },
  { code: '',    name: '临汾',      nameEn: 'Linfen',          airport: '',                   country: '中国' },
  { code: '',    name: '忻州',      nameEn: 'Xinzhou',         airport: '',                   country: '中国' },
  { code: '',    name: '朔州',      nameEn: 'Shuozhou',        airport: '',                   country: '中国' },
  { code: '',    name: '阳泉',      nameEn: 'Yangquan',        airport: '',                   country: '中国' },
  { code: '',    name: '晋城',      nameEn: 'Jincheng',        airport: '',                   country: '中国' },

  // ══ 内蒙古 ══
  { code: 'HET', name: '呼和浩特',  nameEn: 'Hohhot',          airport: '白塔国际机场',       country: '中国' },
  { code: 'BAV', name: '包头',      nameEn: 'Baotou',          airport: '东河机场',           country: '中国' },
  { code: 'DSN', name: '鄂尔多斯',  nameEn: 'Ordos',           airport: '伊金霍洛机场',       country: '中国' },
  { code: 'HLD', name: '呼伦贝尔',  nameEn: 'Hulunbuir',       airport: '海拉尔机场',         country: '中国' },
  { code: 'NZH', name: '满洲里',    nameEn: 'Manzhouli',       airport: '西郊机场',           country: '中国' },
  { code: 'CIF', name: '赤峰',      nameEn: 'Chifeng',         airport: '玉龙机场',           country: '中国' },
  { code: 'TGO', name: '通辽',      nameEn: 'Tongliao',        airport: '通辽机场',           country: '中国' },
  { code: 'HLH', name: '乌兰浩特',  nameEn: 'Ulanhot',         airport: '义勒力特机场',       country: '中国' },
  { code: 'XIL', name: '锡林浩特',  nameEn: 'Xilinhot',        airport: '锡林浩特机场',       country: '中国' },
  { code: 'YIE', name: '阿尔山',    nameEn: 'Arxan',           airport: '伊尔施机场',         country: '中国' },
  { code: 'EJN', name: '额济纳',    nameEn: 'Ejin',            airport: '居延机场',           country: '中国' },
  { code: '',    name: '乌海',      nameEn: 'Wuhai',           airport: '',                   country: '中国' },
  { code: '',    name: '巴彦淖尔',  nameEn: 'Bayannur',        airport: '',                   country: '中国' },

  // ══ 辽宁省 ══
  { code: 'SHE', name: '沈阳',      nameEn: 'Shenyang',        airport: '桃仙国际机场',       country: '中国' },
  { code: 'DLC', name: '大连',      nameEn: 'Dalian',          airport: '周水子国际机场',     country: '中国' },
  { code: 'DDG', name: '丹东',      nameEn: 'Dandong',         airport: '浪头机场',           country: '中国' },
  { code: 'JNZ', name: '锦州',      nameEn: 'Jinzhou',         airport: '小岭子机场',         country: '中国' },
  { code: 'CHG', name: '朝阳',      nameEn: 'Chaoyang',        airport: '朝阳机场',           country: '中国' },
  { code: 'YKH', name: '营口',      nameEn: 'Yingkou',         airport: '兰旗机场',           country: '中国' },
  { code: '',    name: '鞍山',      nameEn: 'Anshan',          airport: '',                   country: '中国' },
  { code: '',    name: '抚顺',      nameEn: 'Fushun',          airport: '',                   country: '中国' },
  { code: '',    name: '本溪',      nameEn: 'Benxi',           airport: '',                   country: '中国' },
  { code: '',    name: '盘锦',      nameEn: 'Panjin',          airport: '',                   country: '中国' },
  { code: '',    name: '葫芦岛',    nameEn: 'Huludao',         airport: '',                   country: '中国' },
  { code: '',    name: '辽阳',      nameEn: 'Liaoyang',        airport: '',                   country: '中国' },
  { code: '',    name: '铁岭',      nameEn: 'Tieling',         airport: '',                   country: '中国' },
  { code: '',    name: '阜新',      nameEn: 'Fuxin',           airport: '',                   country: '中国' },

  // ══ 吉林省 ══
  { code: 'CGQ', name: '长春',      nameEn: 'Changchun',       airport: '龙嘉国际机场',       country: '中国' },
  { code: '',    name: '吉林',      nameEn: 'Jilin',           airport: '',                   country: '中国' },
  { code: 'YNJ', name: '延吉',      nameEn: 'Yanji',           airport: '朝阳川机场',         country: '中国' },
  { code: 'NBS', name: '白山',      nameEn: 'Baishan',         airport: '长白山机场',         country: '中国' },
  { code: 'DBC', name: '白城',      nameEn: 'Baicheng',        airport: '长安机场',           country: '中国' },
  { code: 'TNH', name: '通化',      nameEn: 'Tonghua',         airport: '三源浦机场',         country: '中国' },
  { code: '',    name: '四平',      nameEn: 'Siping',          airport: '',                   country: '中国' },
  { code: '',    name: '辽源',      nameEn: 'Liaoyuan',        airport: '',                   country: '中国' },
  { code: '',    name: '松原',      nameEn: 'Songyuan',        airport: '',                   country: '中国' },

  // ══ 黑龙江省 ══
  { code: 'HRB', name: '哈尔滨',    nameEn: 'Harbin',          airport: '太平国际机场',       country: '中国' },
  { code: 'NDG', name: '齐齐哈尔',  nameEn: 'Qiqihar',         airport: '三家子机场',         country: '中国' },
  { code: 'MDG', name: '牡丹江',    nameEn: 'Mudanjiang',      airport: '海浪机场',           country: '中国' },
  { code: 'JMU', name: '佳木斯',    nameEn: 'Jiamusi',         airport: '东郊机场',           country: '中国' },
  { code: 'DQA', name: '大庆',      nameEn: 'Daqing',          airport: '萨尔图机场',         country: '中国' },
  { code: 'OHE', name: '漠河',      nameEn: 'Mohe',            airport: '古莲机场',           country: '中国' },
  { code: 'LDS', name: '伊春',      nameEn: 'Yichun',          airport: '林都机场',           country: '中国' },
  { code: 'HEK', name: '黑河',      nameEn: 'Heihe',           airport: '嫩江机场',           country: '中国' },
  { code: 'JXA', name: '鸡西',      nameEn: 'Jixi',            airport: '兴凯湖机场',         country: '中国' },
  { code: '',    name: '绥化',      nameEn: 'Suihua',          airport: '',                   country: '中国' },
  { code: '',    name: '双鸭山',    nameEn: 'Shuangyashan',    airport: '',                   country: '中国' },
  { code: '',    name: '七台河',    nameEn: 'Qitaihe',         airport: '',                   country: '中国' },
  { code: '',    name: '鹤岗',      nameEn: 'Hegang',          airport: '',                   country: '中国' },

  // ══ 江苏省 ══
  { code: 'NKG', name: '南京',      nameEn: 'Nanjing',         airport: '禄口国际机场',       country: '中国' },
  { code: '',    name: '苏州',      nameEn: 'Suzhou',          airport: '',                   country: '中国' },
  { code: 'WUX', name: '无锡',      nameEn: 'Wuxi',            airport: '硕放国际机场',       country: '中国' },
  { code: 'CZX', name: '常州',      nameEn: 'Changzhou',       airport: '奔牛机场',           country: '中国' },
  { code: 'XUZ', name: '徐州',      nameEn: 'Xuzhou',          airport: '观音机场',           country: '中国' },
  { code: 'YTY', name: '扬州',      nameEn: 'Yangzhou',        airport: '泰州机场',           country: '中国' },
  { code: 'NTG', name: '南通',      nameEn: 'Nantong',         airport: '兴东机场',           country: '中国' },
  { code: 'LYG', name: '连云港',    nameEn: 'Lianyungang',     airport: '白塔埠机场',         country: '中国' },
  { code: 'YNZ', name: '盐城',      nameEn: 'Yancheng',        airport: '南洋机场',           country: '中国' },
  { code: 'HIA', name: '淮安',      nameEn: 'Huaian',          airport: '涟水机场',           country: '中国' },
  { code: '',    name: '镇江',      nameEn: 'Zhenjiang',       airport: '',                   country: '中国' },
  { code: '',    name: '泰州',      nameEn: 'Taizhou',         airport: '',                   country: '中国' },
  { code: '',    name: '宿迁',      nameEn: 'Suqian',          airport: '',                   country: '中国' },

  // ══ 浙江省 ══
  { code: 'HGH', name: '杭州',      nameEn: 'Hangzhou',        airport: '萧山国际机场',       country: '中国' },
  { code: 'NGB', name: '宁波',      nameEn: 'Ningbo',          airport: '栎社国际机场',       country: '中国' },
  { code: 'WNZ', name: '温州',      nameEn: 'Wenzhou',         airport: '龙湾国际机场',       country: '中国' },
  { code: 'YIW', name: '义乌',      nameEn: 'Yiwu',            airport: '义乌机场',           country: '中国' },
  { code: 'HSN', name: '舟山',      nameEn: 'Zhoushan',        airport: '普陀山机场',         country: '中国' },
  { code: 'HYN', name: '台州',      nameEn: 'Taizhou',         airport: '路桥机场',           country: '中国' },
  { code: 'JUZ', name: '衢州',      nameEn: 'Quzhou',          airport: '衢州机场',           country: '中国' },
  { code: '',    name: '嘉兴',      nameEn: 'Jiaxing',         airport: '',                   country: '中国' },
  { code: '',    name: '湖州',      nameEn: 'Huzhou',          airport: '',                   country: '中国' },
  { code: '',    name: '绍兴',      nameEn: 'Shaoxing',        airport: '',                   country: '中国' },
  { code: '',    name: '金华',      nameEn: 'Jinhua',          airport: '',                   country: '中国' },
  { code: '',    name: '丽水',      nameEn: 'Lishui',          airport: '',                   country: '中国' },

  // ══ 安徽省 ══
  { code: 'HFE', name: '合肥',      nameEn: 'Hefei',           airport: '新桥国际机场',       country: '中国' },
  { code: 'TXN', name: '黄山',      nameEn: 'Huangshan',       airport: '屯溪国际机场',       country: '中国' },
  { code: 'AQG', name: '安庆',      nameEn: 'Anqing',          airport: '天柱山机场',         country: '中国' },
  { code: 'FUG', name: '阜阳',      nameEn: 'Fuyang',          airport: '西关机场',           country: '中国' },
  { code: 'JUH', name: '池州',      nameEn: 'Chizhou',         airport: '九华山机场',         country: '中国' },
  { code: 'WHA', name: '芜湖',      nameEn: 'Wuhu',            airport: '宣州机场',           country: '中国' },
  { code: '',    name: '蚌埠',      nameEn: 'Bengbu',          airport: '',                   country: '中国' },
  { code: '',    name: '马鞍山',    nameEn: 'Maanshan',        airport: '',                   country: '中国' },
  { code: '',    name: '铜陵',      nameEn: 'Tongling',        airport: '',                   country: '中国' },
  { code: '',    name: '淮南',      nameEn: 'Huainan',         airport: '',                   country: '中国' },
  { code: '',    name: '淮北',      nameEn: 'Huaibei',         airport: '',                   country: '中国' },
  { code: '',    name: '六安',      nameEn: 'Luan',            airport: '',                   country: '中国' },
  { code: '',    name: '宿州',      nameEn: 'Suzhou',          airport: '',                   country: '中国' },
  { code: '',    name: '亳州',      nameEn: 'Bozhou',          airport: '',                   country: '中国' },
  { code: '',    name: '滁州',      nameEn: 'Chuzhou',         airport: '',                   country: '中国' },
  { code: '',    name: '宣城',      nameEn: 'Xuancheng',       airport: '',                   country: '中国' },

  // ══ 福建省 ══
  { code: 'FOC', name: '福州',      nameEn: 'Fuzhou',          airport: '长乐国际机场',       country: '中国' },
  { code: 'XMN', name: '厦门',      nameEn: 'Xiamen',          airport: '高崎国际机场',       country: '中国' },
  { code: 'JJN', name: '泉州',      nameEn: 'Quanzhou',        airport: '晋江机场',           country: '中国' },
  { code: 'WUS', name: '武夷山',    nameEn: 'Wuyishan',        airport: '武夷山机场',         country: '中国' },
  { code: '',    name: '漳州',      nameEn: 'Zhangzhou',       airport: '',                   country: '中国' },
  { code: '',    name: '莆田',      nameEn: 'Putian',          airport: '',                   country: '中国' },
  { code: '',    name: '龙岩',      nameEn: 'Longyan',         airport: '',                   country: '中国' },
  { code: '',    name: '三明',      nameEn: 'Sanming',         airport: '',                   country: '中国' },
  { code: '',    name: '宁德',      nameEn: 'Ningde',          airport: '',                   country: '中国' },
  { code: '',    name: '南平',      nameEn: 'Nanping',         airport: '',                   country: '中国' },

  // ══ 江西省 ══
  { code: 'KHN', name: '南昌',      nameEn: 'Nanchang',        airport: '昌北国际机场',       country: '中国' },
  { code: 'JDZ', name: '景德镇',    nameEn: 'Jingdezhen',      airport: '罗家机场',           country: '中国' },
  { code: 'KOW', name: '赣州',      nameEn: 'Ganzhou',         airport: '黄金机场',           country: '中国' },
  { code: 'JGS', name: '井冈山',    nameEn: 'Jinggangshan',    airport: '井冈山机场',         country: '中国' },
  { code: 'SQD', name: '上饶',      nameEn: 'Shangrao',        airport: '三清山机场',         country: '中国' },
  { code: 'YIC', name: '宜春',      nameEn: 'Yichun',          airport: '明月山机场',         country: '中国' },
  { code: '',    name: '九江',      nameEn: 'Jiujiang',        airport: '',                   country: '中国' },
  { code: '',    name: '抚州',      nameEn: 'Fuzhou',          airport: '',                   country: '中国' },
  { code: '',    name: '新余',      nameEn: 'Xinyu',           airport: '',                   country: '中国' },
  { code: '',    name: '萍乡',      nameEn: 'Pingxiang',       airport: '',                   country: '中国' },
  { code: '',    name: '鹰潭',      nameEn: 'Yingtan',         airport: '',                   country: '中国' },
  { code: '',    name: '吉安',      nameEn: 'Jian',            airport: '',                   country: '中国' },

  // ══ 山东省 ══
  { code: 'TNA', name: '济南',      nameEn: 'Jinan',           airport: '遥墙国际机场',       country: '中国' },
  { code: 'TAO', name: '青岛',      nameEn: 'Qingdao',         airport: '胶东国际机场',       country: '中国' },
  { code: 'YNT', name: '烟台',      nameEn: 'Yantai',          airport: '蓬莱国际机场',       country: '中国' },
  { code: 'WEH', name: '威海',      nameEn: 'Weihai',          airport: '大水泊机场',         country: '中国' },
  { code: 'WEF', name: '潍坊',      nameEn: 'Weifang',         airport: '南苑机场',           country: '中国' },
  { code: 'LYI', name: '临沂',      nameEn: 'Linyi',           airport: '启阳机场',           country: '中国' },
  { code: 'JNG', name: '济宁',      nameEn: 'Jining',          airport: '曲阜机场',           country: '中国' },
  { code: 'RIZ', name: '日照',      nameEn: 'Rizhao',          airport: '山字河机场',         country: '中国' },
  { code: 'DOY', name: '东营',      nameEn: 'Dongying',        airport: '胜利机场',           country: '中国' },
  { code: '',    name: '淄博',      nameEn: 'Zibo',            airport: '',                   country: '中国' },
  { code: '',    name: '枣庄',      nameEn: 'Zaozhuang',       airport: '',                   country: '中国' },
  { code: '',    name: '泰安',      nameEn: 'Taian',           airport: '',                   country: '中国' },
  { code: '',    name: '德州',      nameEn: 'Dezhou',          airport: '',                   country: '中国' },
  { code: '',    name: '聊城',      nameEn: 'Liaocheng',       airport: '',                   country: '中国' },
  { code: '',    name: '滨州',      nameEn: 'Binzhou',         airport: '',                   country: '中国' },
  { code: '',    name: '菏泽',      nameEn: 'Heze',            airport: '',                   country: '中国' },

  // ══ 河南省 ══
  { code: 'CGO', name: '郑州',      nameEn: 'Zhengzhou',       airport: '新郑国际机场',       country: '中国' },
  { code: 'LYA', name: '洛阳',      nameEn: 'Luoyang',         airport: '北郊机场',           country: '中国' },
  { code: 'NNY', name: '南阳',      nameEn: 'Nanyang',         airport: '姜营机场',           country: '中国' },
  { code: 'XAI', name: '信阳',      nameEn: 'Xinyang',         airport: '明港机场',           country: '中国' },
  { code: '',    name: '开封',      nameEn: 'Kaifeng',         airport: '',                   country: '中国' },
  { code: '',    name: '安阳',      nameEn: 'Anyang',          airport: '',                   country: '中国' },
  { code: '',    name: '新乡',      nameEn: 'Xinxiang',        airport: '',                   country: '中国' },
  { code: '',    name: '焦作',      nameEn: 'Jiaozuo',         airport: '',                   country: '中国' },
  { code: '',    name: '许昌',      nameEn: 'Xuchang',         airport: '',                   country: '中国' },
  { code: '',    name: '漯河',      nameEn: 'Luohe',           airport: '',                   country: '中国' },
  { code: '',    name: '三门峡',    nameEn: 'Sanmenxia',       airport: '',                   country: '中国' },
  { code: '',    name: '商丘',      nameEn: 'Shangqiu',        airport: '',                   country: '中国' },
  { code: '',    name: '周口',      nameEn: 'Zhoukou',         airport: '',                   country: '中国' },
  { code: '',    name: '驻马店',    nameEn: 'Zhumadian',       airport: '',                   country: '中国' },
  { code: '',    name: '平顶山',    nameEn: 'Pingdingshan',    airport: '',                   country: '中国' },
  { code: '',    name: '鹤壁',      nameEn: 'Hebi',            airport: '',                   country: '中国' },
  { code: '',    name: '濮阳',      nameEn: 'Puyang',          airport: '',                   country: '中国' },

  // ══ 湖北省 ══
  { code: 'WUH', name: '武汉',      nameEn: 'Wuhan',           airport: '天河国际机场',       country: '中国' },
  { code: 'YIH', name: '宜昌',      nameEn: 'Yichang',         airport: '三峡机场',           country: '中国' },
  { code: 'XFN', name: '襄阳',      nameEn: 'Xiangyang',       airport: '刘集机场',           country: '中国' },
  { code: 'ENH', name: '恩施',      nameEn: 'Enshi',           airport: '许家坪机场',         country: '中国' },
  { code: 'WDS', name: '十堰',      nameEn: 'Shiyan',          airport: '武当山机场',         country: '中国' },
  { code: 'HPG', name: '神农架',    nameEn: 'Shennongjia',     airport: '神农架机场',         country: '中国' },
  { code: '',    name: '荆州',      nameEn: 'Jingzhou',        airport: '',                   country: '中国' },
  { code: '',    name: '黄冈',      nameEn: 'Huanggang',       airport: '',                   country: '中国' },
  { code: '',    name: '黄石',      nameEn: 'Huangshi',        airport: '',                   country: '中国' },
  { code: '',    name: '荆门',      nameEn: 'Jingmen',         airport: '',                   country: '中国' },
  { code: '',    name: '孝感',      nameEn: 'Xiaogan',         airport: '',                   country: '中国' },
  { code: '',    name: '咸宁',      nameEn: 'Xianning',        airport: '',                   country: '中国' },
  { code: '',    name: '鄂州',      nameEn: 'Ezhou',           airport: '',                   country: '中国' },
  { code: '',    name: '随州',      nameEn: 'Suizhou',         airport: '',                   country: '中国' },

  // ══ 湖南省 ══
  { code: 'CSX', name: '长沙',      nameEn: 'Changsha',        airport: '黄花国际机场',       country: '中国' },
  { code: 'DYG', name: '张家界',    nameEn: 'Zhangjiajie',     airport: '荷花国际机场',       country: '中国' },
  { code: 'HNY', name: '衡阳',      nameEn: 'Hengyang',        airport: '南岳机场',           country: '中国' },
  { code: 'CGD', name: '常德',      nameEn: 'Changde',         airport: '桃花源机场',         country: '中国' },
  { code: 'HJJ', name: '怀化',      nameEn: 'Huaihua',         airport: '芷江机场',           country: '中国' },
  { code: 'LLF', name: '永州',      nameEn: 'Yongzhou',        airport: '零陵机场',           country: '中国' },
  { code: 'WGN', name: '邵阳',      nameEn: 'Shaoyang',        airport: '武冈机场',           country: '中国' },
  { code: '',    name: '株洲',      nameEn: 'Zhuzhou',         airport: '',                   country: '中国' },
  { code: '',    name: '湘潭',      nameEn: 'Xiangtan',        airport: '',                   country: '中国' },
  { code: '',    name: '岳阳',      nameEn: 'Yueyang',         airport: '',                   country: '中国' },
  { code: '',    name: '益阳',      nameEn: 'Yiyang',          airport: '',                   country: '中国' },
  { code: '',    name: '郴州',      nameEn: 'Chenzhou',        airport: '',                   country: '中国' },
  { code: '',    name: '娄底',      nameEn: 'Loudi',           airport: '',                   country: '中国' },
  { code: '',    name: '湘西',      nameEn: 'Xiangxi',         airport: '',                   country: '中国' },

  // ══ 广东省 ══
  { code: 'CAN', name: '广州',      nameEn: 'Guangzhou',       airport: '白云国际机场',       country: '中国' },
  { code: 'SZX', name: '深圳',      nameEn: 'Shenzhen',        airport: '宝安国际机场',       country: '中国' },
  { code: 'ZUH', name: '珠海',      nameEn: 'Zhuhai',          airport: '金湾机场',           country: '中国' },
  { code: 'SWA', name: '汕头',      nameEn: 'Shantou',         airport: '外砂机场',           country: '中国' },
  { code: 'HUZ', name: '惠州',      nameEn: 'Huizhou',         airport: '平潭机场',           country: '中国' },
  { code: 'ZHA', name: '湛江',      nameEn: 'Zhanjiang',       airport: '吴川机场',           country: '中国' },
  { code: 'MXZ', name: '梅州',      nameEn: 'Meizhou',         airport: '梅县机场',           country: '中国' },
  { code: '',    name: '佛山',      nameEn: 'Foshan',          airport: '',                   country: '中国' },
  { code: '',    name: '东莞',      nameEn: 'Dongguan',        airport: '',                   country: '中国' },
  { code: '',    name: '中山',      nameEn: 'Zhongshan',       airport: '',                   country: '中国' },
  { code: '',    name: '江门',      nameEn: 'Jiangmen',        airport: '',                   country: '中国' },
  { code: '',    name: '肇庆',      nameEn: 'Zhaoqing',        airport: '',                   country: '中国' },
  { code: '',    name: '茂名',      nameEn: 'Maoming',         airport: '',                   country: '中国' },
  { code: '',    name: '阳江',      nameEn: 'Yangjiang',       airport: '',                   country: '中国' },
  { code: '',    name: '韶关',      nameEn: 'Shaoguan',        airport: '',                   country: '中国' },
  { code: '',    name: '清远',      nameEn: 'Qingyuan',        airport: '',                   country: '中国' },
  { code: '',    name: '潮州',      nameEn: 'Chaozhou',        airport: '',                   country: '中国' },
  { code: '',    name: '揭阳',      nameEn: 'Jieyang',         airport: '',                   country: '中国' },
  { code: '',    name: '河源',      nameEn: 'Heyuan',          airport: '',                   country: '中国' },
  { code: '',    name: '汕尾',      nameEn: 'Shanwei',         airport: '',                   country: '中国' },
  { code: '',    name: '云浮',      nameEn: 'Yunfu',           airport: '',                   country: '中国' },

  // ══ 广西 ══
  { code: 'NNG', name: '南宁',      nameEn: 'Nanning',         airport: '吴圩国际机场',       country: '中国' },
  { code: 'KWL', name: '桂林',      nameEn: 'Guilin',          airport: '两江国际机场',       country: '中国' },
  { code: 'BHY', name: '北海',      nameEn: 'Beihai',          airport: '福成机场',           country: '中国' },
  { code: 'LZH', name: '柳州',      nameEn: 'Liuzhou',         airport: '白莲机场',           country: '中国' },
  { code: 'AEB', name: '百色',      nameEn: 'Baise',           airport: '巴马机场',           country: '中国' },
  { code: 'HCJ', name: '河池',      nameEn: 'Hechi',           airport: '金城江机场',         country: '中国' },
  { code: '',    name: '梧州',      nameEn: 'Wuzhou',          airport: '',                   country: '中国' },
  { code: '',    name: '钦州',      nameEn: 'Qinzhou',         airport: '',                   country: '中国' },
  { code: '',    name: '玉林',      nameEn: 'Yulin',           airport: '',                   country: '中国' },
  { code: '',    name: '贵港',      nameEn: 'Guigang',         airport: '',                   country: '中国' },
  { code: '',    name: '贺州',      nameEn: 'Hezhou',          airport: '',                   country: '中国' },
  { code: '',    name: '来宾',      nameEn: 'Laibin',          airport: '',                   country: '中国' },
  { code: '',    name: '崇左',      nameEn: 'Chongzuo',        airport: '',                   country: '中国' },
  { code: '',    name: '防城港',    nameEn: 'Fangchenggang',   airport: '',                   country: '中国' },

  // ══ 海南省 ══
  { code: 'HAK', name: '海口',      nameEn: 'Haikou',          airport: '美兰国际机场',       country: '中国' },
  { code: 'SYX', name: '三亚',      nameEn: 'Sanya',           airport: '凤凰国际机场',       country: '中国' },
  { code: 'BAR', name: '琼海',      nameEn: 'Qionghai',        airport: '博鳌机场',           country: '中国' },
  { code: '',    name: '儋州',      nameEn: 'Danzhou',         airport: '',                   country: '中国' },
  { code: '',    name: '万宁',      nameEn: 'Wanning',         airport: '',                   country: '中国' },
  { code: '',    name: '陵水',      nameEn: 'Lingshui',        airport: '',                   country: '中国' },
  { code: '',    name: '五指山',    nameEn: 'Wuzhishan',       airport: '',                   country: '中国' },

  // ══ 四川省 ══
  { code: 'CTU', name: '成都',      nameEn: 'Chengdu',         airport: '天府国际机场',       country: '中国' },
  { code: 'TFU', name: '成都',      nameEn: 'Chengdu',         airport: '双流国际机场',       country: '中国' },
  { code: 'MIG', name: '绵阳',      nameEn: 'Mianyang',        airport: '南郊机场',           country: '中国' },
  { code: 'LZO', name: '泸州',      nameEn: 'Luzhou',          airport: '云龙机场',           country: '中国' },
  { code: 'YBP', name: '宜宾',      nameEn: 'Yibin',           airport: '五粮液机场',         country: '中国' },
  { code: 'XIC', name: '西昌',      nameEn: 'Xichang',         airport: '青山机场',           country: '中国' },
  { code: 'KGT', name: '康定',      nameEn: 'Kangding',        airport: '康定机场',           country: '中国' },
  { code: 'PZI', name: '攀枝花',    nameEn: 'Panzhihua',       airport: '保安营机场',         country: '中国' },
  { code: 'GYS', name: '广元',      nameEn: 'Guangyuan',       airport: '盘龙机场',           country: '中国' },
  { code: 'NAO', name: '南充',      nameEn: 'Nanchong',        airport: '高坪机场',           country: '中国' },
  { code: 'DAX', name: '达州',      nameEn: 'Dazhou',          airport: '河市机场',           country: '中国' },
  { code: 'JZH', name: '九寨沟',    nameEn: 'Jiuzhaigou',      airport: '黄龙机场',           country: '中国' },
  { code: '',    name: '乐山',      nameEn: 'Leshan',          airport: '',                   country: '中国' },
  { code: '',    name: '眉山',      nameEn: 'Meishan',         airport: '',                   country: '中国' },
  { code: '',    name: '德阳',      nameEn: 'Deyang',          airport: '',                   country: '中国' },
  { code: '',    name: '内江',      nameEn: 'Neijiang',        airport: '',                   country: '中国' },
  { code: '',    name: '自贡',      nameEn: 'Zigong',          airport: '',                   country: '中国' },
  { code: '',    name: '遂宁',      nameEn: 'Suining',         airport: '',                   country: '中国' },
  { code: '',    name: '雅安',      nameEn: 'Yaan',            airport: '',                   country: '中国' },
  { code: '',    name: '资阳',      nameEn: 'Ziyang',          airport: '',                   country: '中国' },
  { code: '',    name: '巴中',      nameEn: 'Bazhong',         airport: '',                   country: '中国' },
  { code: '',    name: '阿坝',      nameEn: 'Aba',             airport: '',                   country: '中国' },
  { code: '',    name: '甘孜',      nameEn: 'Garze',           airport: '',                   country: '中国' },
  { code: '',    name: '凉山',      nameEn: 'Liangshan',       airport: '',                   country: '中国' },
  { code: 'YBP', name: '稻城亚丁',  nameEn: 'Daocheng',        airport: '亚丁机场',           country: '中国' },

  // ══ 贵州省 ══
  { code: 'KWE', name: '贵阳',      nameEn: 'Guiyang',         airport: '龙洞堡国际机场',     country: '中国' },
  { code: 'ZYI', name: '遵义',      nameEn: 'Zunyi',           airport: '茅台机场',           country: '中国' },
  { code: 'TEN', name: '铜仁',      nameEn: 'Tongren',         airport: '凤凰机场',           country: '中国' },
  { code: 'AVA', name: '安顺',      nameEn: 'Anshun',          airport: '黄果树机场',         country: '中国' },
  { code: 'ACX', name: '兴义',      nameEn: 'Xingyi',          airport: '万峰林机场',         country: '中国' },
  { code: 'LLB', name: '荔波',      nameEn: 'Libo',            airport: '荔波机场',           country: '中国' },
  { code: 'LPF', name: '六盘水',    nameEn: 'Liupanshui',      airport: '月照机场',           country: '中国' },
  { code: 'BFJ', name: '毕节',      nameEn: 'Bijie',           airport: '飞雄机场',           country: '中国' },
  { code: '',    name: '凯里',      nameEn: 'Kaili',           airport: '',                   country: '中国' },
  { code: '',    name: '都匀',      nameEn: 'Duyun',           airport: '',                   country: '中国' },

  // ══ 云南省 ══
  { code: 'KMG', name: '昆明',      nameEn: 'Kunming',         airport: '长水国际机场',       country: '中国' },
  { code: 'LJG', name: '丽江',      nameEn: 'Lijiang',         airport: '三义国际机场',       country: '中国' },
  { code: 'JHG', name: '西双版纳',  nameEn: 'Xishuangbanna',   airport: '嘎洒国际机场',       country: '中国' },
  { code: 'DLU', name: '大理',      nameEn: 'Dali',            airport: '大理机场',           country: '中国' },
  { code: 'DIG', name: '香格里拉',  nameEn: 'Shangri-La',      airport: '迪庆机场',           country: '中国' },
  { code: 'TCZ', name: '腾冲',      nameEn: 'Tengchong',       airport: '驼峰机场',           country: '中国' },
  { code: 'LUM', name: '芒市',      nameEn: 'Mangshi',         airport: '芒市机场',           country: '中国' },
  { code: 'BSD', name: '保山',      nameEn: 'Baoshan',         airport: '云端机场',           country: '中国' },
  { code: 'WNH', name: '文山',      nameEn: 'Wenshan',         airport: '普者黑机场',         country: '中国' },
  { code: 'SYM', name: '普洱',      nameEn: 'Puer',            airport: '思茅机场',           country: '中国' },
  { code: 'LNJ', name: '临沧',      nameEn: 'Lincang',         airport: '临沧机场',           country: '中国' },
  { code: 'NLH', name: '泸沽湖',    nameEn: 'Lugu Lake',       airport: '宁蒗机场',           country: '中国' },
  { code: 'JMJ', name: '澜沧',      nameEn: 'Lancang',         airport: '景迈机场',           country: '中国' },
  { code: '',    name: '曲靖',      nameEn: 'Qujing',          airport: '',                   country: '中国' },
  { code: '',    name: '玉溪',      nameEn: 'Yuxi',            airport: '',                   country: '中国' },
  { code: '',    name: '红河',      nameEn: 'Honghe',          airport: '',                   country: '中国' },
  { code: '',    name: '楚雄',      nameEn: 'Chuxiong',        airport: '',                   country: '中国' },
  { code: '',    name: '昭通',      nameEn: 'Zhaotong',        airport: '',                   country: '中国' },
  { code: '',    name: '怒江',      nameEn: 'Nujiang',         airport: '',                   country: '中国' },
  { code: '',    name: '迪庆',      nameEn: 'Diqing',          airport: '',                   country: '中国' },

  // ══ 西藏 ══
  { code: 'LXA', name: '拉萨',      nameEn: 'Lhasa',           airport: '贡嘎机场',           country: '中国' },
  { code: 'LZY', name: '林芝',      nameEn: 'Nyingchi',        airport: '米林机场',           country: '中国' },
  { code: 'RKZ', name: '日喀则',    nameEn: 'Shigatse',        airport: '和平机场',           country: '中国' },
  { code: 'NGQ', name: '阿里',      nameEn: 'Ali',             airport: '昆莎机场',           country: '中国' },
  { code: 'BPX', name: '昌都',      nameEn: 'Chamdo',          airport: '邦达机场',           country: '中国' },
  { code: '',    name: '山南',      nameEn: 'Shannan',         airport: '',                   country: '中国' },
  { code: '',    name: '那曲',      nameEn: 'Nagqu',           airport: '',                   country: '中国' },

  // ══ 陕西省 ══
  { code: 'XIY', name: '西安',      nameEn: "Xi'an",           airport: '咸阳国际机场',       country: '中国' },
  { code: 'ENY', name: '延安',      nameEn: 'Yanan',           airport: '南泥湾机场',         country: '中国' },
  { code: 'HZG', name: '汉中',      nameEn: 'Hanzhong',        airport: '城固机场',           country: '中国' },
  { code: 'UYN', name: '榆林',      nameEn: 'Yulin',           airport: '榆阳机场',           country: '中国' },
  { code: '',    name: '宝鸡',      nameEn: 'Baoji',           airport: '',                   country: '中国' },
  { code: '',    name: '咸阳',      nameEn: 'Xianyang',        airport: '',                   country: '中国' },
  { code: '',    name: '渭南',      nameEn: 'Weinan',          airport: '',                   country: '中国' },
  { code: '',    name: '商洛',      nameEn: 'Shangluo',        airport: '',                   country: '中国' },
  { code: '',    name: '安康',      nameEn: 'Ankang',          airport: '',                   country: '中国' },
  { code: '',    name: '铜川',      nameEn: 'Tongchuan',       airport: '',                   country: '中国' },

  // ══ 甘肃省 ══
  { code: 'LHW', name: '兰州',      nameEn: 'Lanzhou',         airport: '中川国际机场',       country: '中国' },
  { code: 'DNH', name: '敦煌',      nameEn: 'Dunhuang',        airport: '敦煌机场',           country: '中国' },
  { code: 'JGN', name: '嘉峪关',    nameEn: 'Jiayuguan',       airport: '嘉峪关机场',         country: '中国' },
  { code: 'YZY', name: '张掖',      nameEn: 'Zhangye',         airport: '甘州机场',           country: '中国' },
  { code: 'THQ', name: '天水',      nameEn: 'Tianshui',        airport: '麦积山机场',         country: '中国' },
  { code: 'IQN', name: '庆阳',      nameEn: 'Qingyang',        airport: '西峰机场',           country: '中国' },
  { code: 'GXH', name: '甘南',      nameEn: 'Gannan',          airport: '夏河机场',           country: '中国' },
  { code: '',    name: '武威',      nameEn: 'Wuwei',           airport: '',                   country: '中国' },
  { code: '',    name: '白银',      nameEn: 'Baiyin',          airport: '',                   country: '中国' },
  { code: '',    name: '定西',      nameEn: 'Dingxi',          airport: '',                   country: '中国' },
  { code: '',    name: '陇南',      nameEn: 'Longnan',         airport: '',                   country: '中国' },
  { code: '',    name: '平凉',      nameEn: 'Pingliang',       airport: '',                   country: '中国' },
  { code: '',    name: '酒泉',      nameEn: 'Jiuquan',         airport: '',                   country: '中国' },
  { code: '',    name: '金昌',      nameEn: 'Jinchang',        airport: '',                   country: '中国' },
  { code: '',    name: '临夏',      nameEn: 'Linxia',          airport: '',                   country: '中国' },

  // ══ 青海省 ══
  { code: 'XNN', name: '西宁',      nameEn: 'Xining',          airport: '曹家堡国际机场',     country: '中国' },
  { code: 'GOQ', name: '格尔木',    nameEn: 'Golmud',          airport: '格尔木机场',         country: '中国' },
  { code: 'YUS', name: '玉树',      nameEn: 'Yushu',           airport: '巴塘机场',           country: '中国' },
  { code: '',    name: '海东',      nameEn: 'Haidong',         airport: '',                   country: '中国' },
  { code: '',    name: '海北',      nameEn: 'Haibei',          airport: '',                   country: '中国' },
  { code: '',    name: '海西',      nameEn: 'Haixi',           airport: '',                   country: '中国' },
  { code: '',    name: '海南州',    nameEn: 'Hainan',          airport: '',                   country: '中国' },
  { code: '',    name: '黄南',      nameEn: 'Huangnan',        airport: '',                   country: '中国' },
  { code: '',    name: '果洛',      nameEn: 'Guoluo',          airport: '',                   country: '中国' },

  // ══ 宁夏 ══
  { code: 'INC', name: '银川',      nameEn: 'Yinchuan',        airport: '河东国际机场',       country: '中国' },
  { code: 'ZHY', name: '中卫',      nameEn: 'Zhongwei',        airport: '沙坡头机场',         country: '中国' },
  { code: 'GYU', name: '固原',      nameEn: 'Guyuan',          airport: '六盘山机场',         country: '中国' },
  { code: '',    name: '吴忠',      nameEn: 'Wuzhong',         airport: '',                   country: '中国' },
  { code: '',    name: '石嘴山',    nameEn: 'Shizuishan',      airport: '',                   country: '中国' },

  // ══ 新疆 ══
  { code: 'URC', name: '乌鲁木齐',  nameEn: 'Urumqi',          airport: '地窝堡国际机场',     country: '中国' },
  { code: 'KHG', name: '喀什',      nameEn: 'Kashgar',         airport: '喀什机场',           country: '中国' },
  { code: 'AAT', name: '阿勒泰',    nameEn: 'Altay',           airport: '阿勒泰机场',         country: '中国' },
  { code: 'YIN', name: '伊宁',      nameEn: 'Yining',          airport: '伊宁机场',           country: '中国' },
  { code: 'KRL', name: '库尔勒',    nameEn: 'Korla',           airport: '库尔勒机场',         country: '中国' },
  { code: 'HTN', name: '和田',      nameEn: 'Hotan',           airport: '和田机场',           country: '中国' },
  { code: 'KRY', name: '克拉玛依',  nameEn: 'Karamay',         airport: '克拉玛依机场',       country: '中国' },
  { code: 'NLT', name: '那拉提',    nameEn: 'Nalati',          airport: '那拉提机场',         country: '中国' },
  { code: 'TCG', name: '塔城',      nameEn: 'Tacheng',         airport: '塔城机场',           country: '中国' },
  { code: 'AKU', name: '阿克苏',    nameEn: 'Aksu',            airport: '阿克苏机场',         country: '中国' },
  { code: 'KCA', name: '库车',      nameEn: 'Kuche',           airport: '库车机场',           country: '中国' },
  { code: '',    name: '吐鲁番',    nameEn: 'Turpan',          airport: '',                   country: '中国' },
  { code: '',    name: '哈密',      nameEn: 'Hami',            airport: '',                   country: '中国' },
  { code: '',    name: '博尔塔拉',  nameEn: 'Bortala',         airport: '',                   country: '中国' },
  { code: '',    name: '昌吉',      nameEn: 'Changji',         airport: '',                   country: '中国' },
  { code: '',    name: '巴音郭楞',  nameEn: 'Bayingolin',      airport: '',                   country: '中国' },
  { code: '',    name: '克孜勒苏',  nameEn: 'Kizilsu',         airport: '',                   country: '中国' },

  // ══ 澳门 ══
  { code: 'MFM', name: '澳门',      nameEn: 'Macau',           airport: '澳门国际机场',       country: '中国' },

  // ══ 香港 / 台湾 ══
  { code: 'HKG', name: '香港',      nameEn: 'Hong Kong',       airport: '赤鱲角国际机场',     country: '中国香港' },
  { code: 'TPE', name: '台北',      nameEn: 'Taipei',          airport: '桃园国际机场',       country: '中国台湾' },
  { code: 'TSA', name: '台北',      nameEn: 'Taipei',          airport: '松山机场',           country: '中国台湾' },
  { code: 'KHH', name: '高雄',      nameEn: 'Kaohsiung',       airport: '小港国际机场',       country: '中国台湾' },
  { code: 'TNN', name: '台南',      nameEn: 'Tainan',          airport: '台南机场',           country: '中国台湾' },
  { code: 'HUN', name: '花莲',      nameEn: 'Hualien',         airport: '花莲机场',           country: '中国台湾' },
  { code: 'TTT', name: '台东',      nameEn: 'Taitung',         airport: '台东机场',           country: '中国台湾' },

  // ══ 日本 ══
  { code: 'NRT', name: '东京',      nameEn: 'Tokyo',           airport: '成田国际机场',       country: '日本' },
  { code: 'HND', name: '东京',      nameEn: 'Tokyo',           airport: '羽田机场',           country: '日本' },
  { code: 'KIX', name: '大阪',      nameEn: 'Osaka',           airport: '关西国际机场',       country: '日本' },
  { code: 'ITM', name: '大阪',      nameEn: 'Osaka',           airport: '伊丹机场',           country: '日本' },
  { code: 'CTS', name: '札幌',      nameEn: 'Sapporo',         airport: '新千岁机场',         country: '日本' },
  { code: 'FUK', name: '福冈',      nameEn: 'Fukuoka',         airport: '福冈机场',           country: '日本' },
  { code: 'NGO', name: '名古屋',    nameEn: 'Nagoya',          airport: '中部国际机场',       country: '日本' },
  { code: 'OKA', name: '冲绳',      nameEn: 'Okinawa',         airport: '那霸机场',           country: '日本' },
  { code: 'HIJ', name: '广岛',      nameEn: 'Hiroshima',       airport: '广岛机场',           country: '日本' },
  { code: 'SDJ', name: '仙台',      nameEn: 'Sendai',          airport: '仙台机场',           country: '日本' },
  { code: 'KOJ', name: '鹿儿岛',    nameEn: 'Kagoshima',       airport: '鹿儿岛机场',         country: '日本' },
  { code: 'KMQ', name: '小松',      nameEn: 'Komatsu',         airport: '小松机场',           country: '日本' },
  { code: 'AOJ', name: '青森',      nameEn: 'Aomori',          airport: '青森机场',           country: '日本' },
  { code: 'AKJ', name: '旭川',      nameEn: 'Asahikawa',       airport: '旭川机场',           country: '日本' },

  // ══ 韩国 ══
  { code: 'ICN', name: '首尔',      nameEn: 'Seoul',           airport: '仁川国际机场',       country: '韩国' },
  { code: 'GMP', name: '首尔',      nameEn: 'Seoul',           airport: '金浦机场',           country: '韩国' },
  { code: 'PUS', name: '釜山',      nameEn: 'Busan',           airport: '金海国际机场',       country: '韩国' },
  { code: 'CJU', name: '济州',      nameEn: 'Jeju',            airport: '济州国际机场',       country: '韩国' },

  // ══ 东南亚 ══
  { code: 'SIN', name: '新加坡',    nameEn: 'Singapore',       airport: '樟宜国际机场',       country: '新加坡' },
  { code: 'BKK', name: '曼谷',      nameEn: 'Bangkok',         airport: '素万那普机场',       country: '泰国' },
  { code: 'DMK', name: '曼谷',      nameEn: 'Bangkok',         airport: '廊曼国际机场',       country: '泰国' },
  { code: 'HKT', name: '普吉',      nameEn: 'Phuket',          airport: '普吉国际机场',       country: '泰国' },
  { code: 'CNX', name: '清迈',      nameEn: 'Chiang Mai',      airport: '清迈国际机场',       country: '泰国' },
  { code: 'USM', name: '苏梅',      nameEn: 'Koh Samui',       airport: '苏梅机场',           country: '泰国' },
  { code: 'KBV', name: '甲米',      nameEn: 'Krabi',           airport: '甲米机场',           country: '泰国' },
  { code: 'KUL', name: '吉隆坡',    nameEn: 'Kuala Lumpur',    airport: '吉隆坡国际机场',     country: '马来西亚' },
  { code: 'PEN', name: '槟城',      nameEn: 'Penang',          airport: '槟城国际机场',       country: '马来西亚' },
  { code: 'BKI', name: '亚庇',      nameEn: 'Kota Kinabalu',   airport: '亚庇国际机场',       country: '马来西亚' },
  { code: 'LGK', name: '兰卡威',    nameEn: 'Langkawi',        airport: '兰卡威国际机场',     country: '马来西亚' },
  { code: 'DPS', name: '巴厘岛',    nameEn: 'Bali',            airport: '恩古拉赖国际机场',   country: '印度尼西亚' },
  { code: 'CGK', name: '雅加达',    nameEn: 'Jakarta',         airport: '苏加诺-哈达机场',    country: '印度尼西亚' },
  { code: 'SUB', name: '泗水',      nameEn: 'Surabaya',        airport: '朱安达国际机场',     country: '印度尼西亚' },
  { code: 'JOG', name: '日惹',      nameEn: 'Yogyakarta',      airport: '阿迪苏西普托机场',   country: '印度尼西亚' },
  { code: 'LOP', name: '龙目岛',    nameEn: 'Lombok',          airport: '龙目岛国际机场',     country: '印度尼西亚' },
  { code: 'MNL', name: '马尼拉',    nameEn: 'Manila',          airport: '尼诺伊·阿基诺机场',  country: '菲律宾' },
  { code: 'CEB', name: '宿务',      nameEn: 'Cebu',            airport: '麦克坦-宿务国际机场',country: '菲律宾' },
  { code: 'MPH', name: '长滩岛',    nameEn: 'Boracay',         airport: '卡利博机场',         country: '菲律宾' },
  { code: 'PPS', name: '巴拉望',    nameEn: 'Puerto Princesa', airport: '巴拉望国际机场',     country: '菲律宾' },
  { code: 'SGN', name: '胡志明市',  nameEn: 'Ho Chi Minh',     airport: '新山一国际机场',     country: '越南' },
  { code: 'HAN', name: '河内',      nameEn: 'Hanoi',           airport: '内排国际机场',       country: '越南' },
  { code: 'DAD', name: '岘港',      nameEn: 'Da Nang',         airport: '岘港国际机场',       country: '越南' },
  { code: 'CXR', name: '芽庄',      nameEn: 'Nha Trang',       airport: '金兰国际机场',       country: '越南' },
  { code: 'PQC', name: '富国岛',    nameEn: 'Phu Quoc',        airport: '富国国际机场',       country: '越南' },
  { code: 'PNH', name: '金边',      nameEn: 'Phnom Penh',      airport: '金边国际机场',       country: '柬埔寨' },
  { code: 'REP', name: '暹粒',      nameEn: 'Siem Reap',       airport: '暹粒机场',           country: '柬埔寨' },
  { code: 'RGN', name: '仰光',      nameEn: 'Yangon',          airport: '仰光国际机场',       country: '缅甸' },
  { code: 'NYU', name: '蒲甘',      nameEn: 'Bagan',           airport: '曼德勒机场',         country: '缅甸' },
  { code: 'VTE', name: '万象',      nameEn: 'Vientiane',       airport: '瓦岱国际机场',       country: '老挝' },
  { code: 'LPQ', name: '龙坡邦',    nameEn: 'Luang Prabang',   airport: '龙坡邦机场',         country: '老挝' },
  { code: 'MLE', name: '马尔代夫',  nameEn: 'Maldives',        airport: '马累国际机场',       country: '马尔代夫' },
  { code: 'CMB', name: '科伦坡',    nameEn: 'Colombo',         airport: '班达拉奈克机场',     country: '斯里兰卡' },
  { code: 'HRI', name: '汉班托塔',  nameEn: 'Hambantota',      airport: '马塔拉机场',         country: '斯里兰卡' },
  { code: 'UTP', name: '芭提雅',    nameEn: 'Pattaya',         airport: '乌塔堡机场',         country: '泰国' },

  // ══ 中东 ══
  { code: 'DXB', name: '迪拜',      nameEn: 'Dubai',           airport: '迪拜国际机场',       country: '阿联酋' },
  { code: 'AUH', name: '阿布扎比',  nameEn: 'Abu Dhabi',       airport: '阿布扎比国际机场',   country: '阿联酋' },
  { code: 'DOH', name: '多哈',      nameEn: 'Doha',            airport: '哈马德国际机场',     country: '卡塔尔' },
  { code: 'IST', name: '伊斯坦布尔',nameEn: 'Istanbul',        airport: '伊斯坦布尔机场',     country: '土耳其' },
  { code: 'AYT', name: '安塔利亚',  nameEn: 'Antalya',         airport: '安塔利亚机场',       country: '土耳其' },
  { code: 'TLV', name: '特拉维夫',  nameEn: 'Tel Aviv',        airport: '本古里安机场',       country: '以色列' },
  { code: 'RUH', name: '利雅得',    nameEn: 'Riyadh',          airport: '阿卜杜勒阿齐兹机场', country: '沙特阿拉伯' },
  { code: 'JED', name: '吉达',      nameEn: 'Jeddah',          airport: '阿卜杜勒阿齐兹国王机场', country: '沙特阿拉伯' },

  // ══ 欧洲 ══
  { code: 'CDG', name: '巴黎',      nameEn: 'Paris',           airport: '戴高乐国际机场',     country: '法国' },
  { code: 'ORY', name: '巴黎',      nameEn: 'Paris',           airport: '奥利机场',           country: '法国' },
  { code: 'NCE', name: '尼斯',      nameEn: 'Nice',            airport: '尼斯蔚蓝海岸机场',   country: '法国' },
  { code: 'LHR', name: '伦敦',      nameEn: 'London',          airport: '希思罗机场',         country: '英国' },
  { code: 'LGW', name: '伦敦',      nameEn: 'London',          airport: '盖特威克机场',       country: '英国' },
  { code: 'EDI', name: '爱丁堡',    nameEn: 'Edinburgh',       airport: '爱丁堡机场',         country: '英国' },
  { code: 'MAN', name: '曼彻斯特',  nameEn: 'Manchester',      airport: '曼彻斯特机场',       country: '英国' },
  { code: 'FCO', name: '罗马',      nameEn: 'Rome',            airport: '菲乌米奇诺机场',     country: '意大利' },
  { code: 'MXP', name: '米兰',      nameEn: 'Milan',           airport: '马尔彭萨机场',       country: '意大利' },
  { code: 'VCE', name: '威尼斯',    nameEn: 'Venice',          airport: '威尼斯马可波罗机场', country: '意大利' },
  { code: 'FLR', name: '佛罗伦萨',  nameEn: 'Florence',        airport: '佩雷托拉机场',       country: '意大利' },
  { code: 'NAP', name: '那不勒斯',  nameEn: 'Naples',          airport: '那不勒斯卡波迪奇诺机场', country: '意大利' },
  { code: 'BCN', name: '巴塞罗那',  nameEn: 'Barcelona',       airport: '埃尔普拉特机场',     country: '西班牙' },
  { code: 'MAD', name: '马德里',    nameEn: 'Madrid',          airport: '巴拉哈斯机场',       country: '西班牙' },
  { code: 'PMI', name: '马略卡',    nameEn: 'Mallorca',        airport: '帕尔马机场',         country: '西班牙' },
  { code: 'AMS', name: '阿姆斯特丹',nameEn: 'Amsterdam',       airport: '史基浦机场',         country: '荷兰' },
  { code: 'FRA', name: '法兰克福',  nameEn: 'Frankfurt',       airport: '法兰克福国际机场',   country: '德国' },
  { code: 'MUC', name: '慕尼黑',    nameEn: 'Munich',          airport: '慕尼黑机场',         country: '德国' },
  { code: 'BER', name: '柏林',      nameEn: 'Berlin',          airport: '勃兰登堡机场',       country: '德国' },
  { code: 'VIE', name: '维也纳',    nameEn: 'Vienna',          airport: '维也纳国际机场',     country: '奥地利' },
  { code: 'ZRH', name: '苏黎世',    nameEn: 'Zurich',          airport: '苏黎世机场',         country: '瑞士' },
  { code: 'GVA', name: '日内瓦',    nameEn: 'Geneva',          airport: '日内瓦科万坦机场',   country: '瑞士' },
  { code: 'BRU', name: '布鲁塞尔',  nameEn: 'Brussels',        airport: '布鲁塞尔机场',       country: '比利时' },
  { code: 'CPH', name: '哥本哈根',  nameEn: 'Copenhagen',      airport: '哥本哈根机场',       country: '丹麦' },
  { code: 'ARN', name: '斯德哥尔摩',nameEn: 'Stockholm',       airport: '阿兰达机场',         country: '瑞典' },
  { code: 'OSL', name: '奥斯陆',    nameEn: 'Oslo',            airport: '加德莫恩机场',       country: '挪威' },
  { code: 'HEL', name: '赫尔辛基',  nameEn: 'Helsinki',        airport: '万塔机场',           country: '芬兰' },
  { code: 'KEF', name: '雷克雅未克',nameEn: 'Reykjavik',       airport: '凯夫拉维克机场',     country: '冰岛' },
  { code: 'PRG', name: '布拉格',    nameEn: 'Prague',          airport: '瓦茨拉夫哈维尔机场', country: '捷克' },
  { code: 'BUD', name: '布达佩斯',  nameEn: 'Budapest',        airport: '费伦茨·李斯特机场',  country: '匈牙利' },
  { code: 'WAW', name: '华沙',      nameEn: 'Warsaw',          airport: '肖邦机场',           country: '波兰' },
  { code: 'LIS', name: '里斯本',    nameEn: 'Lisbon',          airport: '乌姆贝托·德尔加多机场', country: '葡萄牙' },
  { code: 'ATH', name: '雅典',      nameEn: 'Athens',          airport: '埃莱夫塞里奥斯·韦尼泽洛斯机场', country: '希腊' },
  { code: 'HER', name: '克里特',    nameEn: 'Crete',           airport: '伊拉克利翁机场',     country: '希腊' },
  { code: 'DUB', name: '都柏林',    nameEn: 'Dublin',          airport: '都柏林机场',         country: '爱尔兰' },
  { code: 'OTP', name: '布加勒斯特',nameEn: 'Bucharest',       airport: '亨利·科安达国际机场',country: '罗马尼亚' },
  { code: 'SOF', name: '索菲亚',    nameEn: 'Sofia',           airport: '索菲亚机场',         country: '保加利亚' },
  { code: 'DUB', name: '都柏林',    nameEn: 'Dublin',          airport: '都柏林机场',         country: '爱尔兰' },
  { code: 'SKG', name: '塞萨洛尼基',nameEn: 'Thessaloniki',    airport: '马其顿机场',         country: '希腊' },
  { code: 'SVO', name: '莫斯科',    nameEn: 'Moscow',          airport: '谢列梅捷沃机场',     country: '俄罗斯' },
  { code: 'LED', name: '圣彼得堡',  nameEn: 'St. Petersburg',  airport: '普尔科沃机场',       country: '俄罗斯' },

  // ══ 大洋洲 ══
  { code: 'SYD', name: '悉尼',      nameEn: 'Sydney',          airport: '金斯福德·史密斯机场',country: '澳大利亚' },
  { code: 'MEL', name: '墨尔本',    nameEn: 'Melbourne',       airport: '图拉马林机场',       country: '澳大利亚' },
  { code: 'BNE', name: '布里斯班',  nameEn: 'Brisbane',        airport: '布里斯班机场',       country: '澳大利亚' },
  { code: 'PER', name: '珀斯',      nameEn: 'Perth',           airport: '珀斯机场',           country: '澳大利亚' },
  { code: 'ADL', name: '阿德莱德',  nameEn: 'Adelaide',        airport: '阿德莱德机场',       country: '澳大利亚' },
  { code: 'CNS', name: '凯恩斯',    nameEn: 'Cairns',          airport: '凯恩斯机场',         country: '澳大利亚' },
  { code: 'OOL', name: '黄金海岸',  nameEn: 'Gold Coast',      airport: '黄金海岸机场',       country: '澳大利亚' },
  { code: 'AKL', name: '奥克兰',    nameEn: 'Auckland',        airport: '奥克兰国际机场',     country: '新西兰' },
  { code: 'ZQN', name: '皇后镇',    nameEn: 'Queenstown',      airport: '皇后镇机场',         country: '新西兰' },
  { code: 'CHC', name: '基督城',    nameEn: 'Christchurch',    airport: '基督城机场',         country: '新西兰' },
  { code: 'WLG', name: '惠灵顿',    nameEn: 'Wellington',      airport: '惠灵顿机场',         country: '新西兰' },

  // ══ 美洲 ══
  { code: 'JFK', name: '纽约',      nameEn: 'New York',        airport: '肯尼迪国际机场',     country: '美国' },
  { code: 'LGA', name: '纽约',      nameEn: 'New York',        airport: '拉瓜迪亚机场',       country: '美国' },
  { code: 'LAX', name: '洛杉矶',    nameEn: 'Los Angeles',     airport: '洛杉矶国际机场',     country: '美国' },
  { code: 'SFO', name: '旧金山',    nameEn: 'San Francisco',   airport: '旧金山国际机场',     country: '美国' },
  { code: 'LAS', name: '拉斯维加斯',nameEn: 'Las Vegas',       airport: '哈利·里德国际机场',  country: '美国' },
  { code: 'ORD', name: '芝加哥',    nameEn: 'Chicago',         airport: '奥黑尔国际机场',     country: '美国' },
  { code: 'MIA', name: '迈阿密',    nameEn: 'Miami',           airport: '迈阿密国际机场',     country: '美国' },
  { code: 'HNL', name: '夏威夷',    nameEn: 'Hawaii',          airport: '檀香山国际机场',     country: '美国' },
  { code: 'SEA', name: '西雅图',    nameEn: 'Seattle',         airport: '西塔克机场',         country: '美国' },
  { code: 'BOS', name: '波士顿',    nameEn: 'Boston',          airport: '洛根机场',           country: '美国' },
  { code: 'IAD', name: '华盛顿',    nameEn: 'Washington',      airport: '杜勒斯机场',         country: '美国' },
  { code: 'YYZ', name: '多伦多',    nameEn: 'Toronto',         airport: '皮尔逊国际机场',     country: '加拿大' },
  { code: 'YVR', name: '温哥华',    nameEn: 'Vancouver',       airport: '温哥华国际机场',     country: '加拿大' },
  { code: 'YUL', name: '蒙特利尔',  nameEn: 'Montreal',        airport: '特鲁多机场',         country: '加拿大' },
  { code: 'MEX', name: '墨西哥城',  nameEn: 'Mexico City',     airport: '华雷斯机场',         country: '墨西哥' },
  { code: 'CUN', name: '坎昆',      nameEn: 'Cancun',          airport: '坎昆国际机场',       country: '墨西哥' },
  { code: 'GRU', name: '圣保罗',    nameEn: 'Sao Paulo',       airport: '瓜鲁柳斯机场',       country: '巴西' },
  { code: 'GIG', name: '里约热内卢',nameEn: 'Rio de Janeiro',  airport: '甘萨力诺机场',       country: '巴西' },
  { code: 'EZE', name: '布宜诺斯艾利斯', nameEn: 'Buenos Aires', airport: '埃塞萨机场',       country: '阿根廷' },
  { code: 'LIM', name: '利马',      nameEn: 'Lima',            airport: '豪尔赫查韦斯机场',   country: '秘鲁' },
  { code: 'BOG', name: '波哥大',    nameEn: 'Bogota',          airport: '埃尔多拉多机场',     country: '哥伦比亚' },

  // ══ 南亚 ══
  { code: 'DEL', name: '新德里',    nameEn: 'New Delhi',       airport: '英迪拉·甘地机场',    country: '印度' },
  { code: 'BOM', name: '孟买',      nameEn: 'Mumbai',          airport: '贾特拉帕蒂·希瓦吉机场', country: '印度' },
  { code: 'JAI', name: '斋普尔',    nameEn: 'Jaipur',          airport: '斋普尔机场',         country: '印度' },
  { code: 'CCU', name: '加尔各答',  nameEn: 'Kolkata',         airport: '内塔吉苏巴斯·钱德拉机场', country: '印度' },
  { code: 'BLR', name: '班加罗尔',  nameEn: 'Bangalore',       airport: '肯佩戈达机场',       country: '印度' },
  { code: 'GOI', name: '果阿',      nameEn: 'Goa',             airport: '达博林机场',         country: '印度' },
  { code: 'AMD', name: '艾哈迈达巴德', nameEn: 'Ahmedabad',    airport: '萨达尔·瓦拉巴伊机场',country: '印度' },
  { code: 'KTM', name: '加德满都',  nameEn: 'Kathmandu',       airport: '特里布万机场',       country: '尼泊尔' },

  // ══ 非洲 ══
  { code: 'CAI', name: '开罗',      nameEn: 'Cairo',           airport: '开罗国际机场',       country: '埃及' },
  { code: 'HRG', name: '赫尔格达',  nameEn: 'Hurghada',        airport: '赫尔格达机场',       country: '埃及' },
  { code: 'SSH', name: '沙姆沙伊赫',nameEn: 'Sharm El Sheikh', airport: '沙姆沙伊赫机场',     country: '埃及' },
  { code: 'RAK', name: '马拉喀什',  nameEn: 'Marrakech',       airport: '门纳拉机场',         country: '摩洛哥' },
  { code: 'CMN', name: '卡萨布兰卡',nameEn: 'Casablanca',      airport: '穆罕默德五世机场',   country: '摩洛哥' },
  { code: 'NBO', name: '内罗毕',    nameEn: 'Nairobi',         airport: '乔莫·肯雅塔机场',    country: '肯尼亚' },
  { code: 'JNB', name: '约翰内斯堡',nameEn: 'Johannesburg',    airport: '奥利弗·坦博机场',    country: '南非' },
  { code: 'CPT', name: '开普敦',    nameEn: 'Cape Town',       airport: '开普敦机场',         country: '南非' },
  { code: 'ZNZ', name: '桑给巴尔',  nameEn: 'Zanzibar',        airport: '阿贝德·卡鲁姆机场',  country: '坦桑尼亚' },
  { code: 'DAR', name: '达累斯萨拉姆', nameEn: 'Dar es Salaam', airport: '朱利叶斯·尼雷尔机场', country: '坦桑尼亚' },

  // ══ 中亚 ══
  { code: 'ALA', name: '阿拉木图',  nameEn: 'Almaty',          airport: '阿拉木图机场',       country: '哈萨克斯坦' },
  { code: 'TAS', name: '塔什干',    nameEn: 'Tashkent',        airport: '塔什干机场',         country: '乌兹别克斯坦' },
  { code: 'SKD', name: '撒马尔罕',  nameEn: 'Samarkand',       airport: '撒马尔罕机场',       country: '乌兹别克斯坦' },
]

export function findCityByCode(code: string): CityOption | undefined {
  if (!code) return undefined
  return POPULAR_CITIES.find((c) => c.code === code)
}

export interface SearchResult {
  type:  'city' | 'airport'
  city:  CityOption
  label: string
  sub:   string
}

export function searchCities(query: string): SearchResult[] {
  const q = query.toLowerCase().trim()

  const seen = new Set<string>()
  const results: SearchResult[] = []

  for (const c of POPULAR_CITIES) {
    if (seen.has(c.name)) continue
    if (!q || c.name.includes(q) || c.nameEn.toLowerCase().includes(q) || (c.country ?? '').includes(q)) {
      seen.add(c.name)
      const primaryCode = CITY_PRIMARY[c.name] ?? c.code
      // 对无机场城市（code 为空），直接用当前条目作为主城市
      const primaryCity = primaryCode
        ? (POPULAR_CITIES.find((p) => p.code === primaryCode) ?? c)
        : c
      results.push({ type: 'city', city: primaryCity, label: c.name, sub: primaryCity.country ?? '城市' })
    }
  }

  return q ? results.slice(0, 20) : results
}

export function getAirportsByCity(cityName: string): CityOption[] {
  return POPULAR_CITIES.filter((c) => c.name === cityName && c.code !== '')
}

/* ============================================================
   高铁站数据 / Train Station data
   每个城市列出 1-2 个最常用高铁站
   ============================================================ */

export const TRAIN_STATIONS: Record<string, string[]> = {
  // ── 直辖市 ──
  '北京':     ['北京南站', '北京西站'],
  '上海':     ['上海虹桥站', '上海站'],
  '天津':     ['天津站', '天津西站'],
  '重庆':     ['重庆北站', '重庆西站'],

  // ── 河北省 ──
  '石家庄':   ['石家庄站'],
  '唐山':     ['唐山站'],
  '秦皇岛':   ['秦皇岛站'],
  '邯郸':     ['邯郸东站'],
  '保定':     ['保定东站'],
  '张家口':   ['张家口站'],
  '承德':     ['承德南站'],
  '沧州':     ['沧州西站'],
  '廊坊':     ['廊坊站'],
  '衡水':     ['衡水北站'],
  '邢台':     ['邢台东站'],

  // ── 山西省 ──
  '太原':     ['太原南站'],
  '大同':     ['大同南站'],
  '运城':     ['运城北站'],
  '长治':     ['长治东站'],
  '晋中':     ['晋中站'],
  '临汾':     ['临汾西站'],
  '忻州':     ['忻州西站'],
  '朔州':     ['朔州站'],
  '阳泉':     ['阳泉北站'],
  '晋城':     ['晋城东站'],

  // ── 内蒙古 ──
  '呼和浩特': ['呼和浩特东站'],
  '包头':     ['包头站'],
  '鄂尔多斯': ['鄂尔多斯站'],
  '赤峰':     ['赤峰西站'],
  '通辽':     ['通辽站'],
  '乌兰浩特': ['乌兰浩特站'],
  '乌海':     ['乌海站'],
  '巴彦淖尔': ['临河站'],

  // ── 辽宁省 ──
  '沈阳':     ['沈阳北站', '沈阳站'],
  '大连':     ['大连北站', '大连站'],
  '丹东':     ['丹东站'],
  '锦州':     ['锦州南站'],
  '鞍山':     ['鞍山西站'],
  '营口':     ['营口东站'],
  '盘锦':     ['盘锦站'],
  '葫芦岛':   ['葫芦岛北站'],
  '辽阳':     ['辽阳站'],
  '铁岭':     ['铁岭西站'],
  '朝阳':     ['朝阳站'],
  '抚顺':     ['抚顺北站'],
  '本溪':     ['本溪站'],
  '阜新':     ['阜新站'],

  // ── 吉林省 ──
  '长春':     ['长春站', '长春西站'],
  '吉林':     ['吉林站'],
  '延吉':     ['延吉西站'],
  '四平':     ['四平东站'],
  '松原':     ['松原站'],
  '白城':     ['白城站'],
  '通化':     ['通化站'],
  '辽源':     ['辽源站'],

  // ── 黑龙江省 ──
  '哈尔滨':   ['哈尔滨西站', '哈尔滨站'],
  '齐齐哈尔': ['齐齐哈尔南站'],
  '牡丹江':   ['牡丹江站'],
  '佳木斯':   ['佳木斯站'],
  '大庆':     ['大庆西站'],
  '绥化':     ['绥化站'],
  '鸡西':     ['鸡西站'],
  '双鸭山':   ['双鸭山站'],

  // ── 江苏省 ──
  '南京':     ['南京南站', '南京站'],
  '苏州':     ['苏州北站', '苏州站'],
  '无锡':     ['无锡东站', '无锡站'],
  '常州':     ['常州北站'],
  '徐州':     ['徐州东站'],
  '扬州':     ['扬州东站'],
  '南通':     ['南通站'],
  '连云港':   ['连云港站'],
  '盐城':     ['盐城站'],
  '淮安':     ['淮安东站'],
  '镇江':     ['镇江南站'],
  '泰州':     ['泰州站'],
  '宿迁':     ['宿迁站'],

  // ── 浙江省 ──
  '杭州':     ['杭州东站', '杭州西站'],
  '宁波':     ['宁波站'],
  '温州':     ['温州南站'],
  '义乌':     ['义乌站'],
  '嘉兴':     ['嘉兴南站'],
  '湖州':     ['湖州站'],
  '绍兴':     ['绍兴北站'],
  '金华':     ['金华站'],
  '台州':     ['台州站'],
  '衢州':     ['衢州站'],
  '舟山':     ['舟山站'],
  '丽水':     ['丽水站'],

  // ── 安徽省 ──
  '合肥':     ['合肥南站', '合肥站'],
  '黄山':     ['黄山北站'],
  '安庆':     ['安庆站'],
  '阜阳':     ['阜阳西站'],
  '芜湖':     ['芜湖站'],
  '蚌埠':     ['蚌埠南站'],
  '马鞍山':   ['马鞍山东站'],
  '铜陵':     ['铜陵站'],
  '淮南':     ['淮南东站'],
  '淮北':     ['淮北站'],
  '六安':     ['六安站'],
  '宿州':     ['宿州东站'],
  '亳州':     ['亳州南站'],
  '滁州':     ['滁州站'],
  '宣城':     ['宣城站'],
  '池州':     ['池州站'],

  // ── 福建省 ──
  '福州':     ['福州站', '福州南站'],
  '厦门':     ['厦门北站', '厦门站'],
  '泉州':     ['泉州站'],
  '漳州':     ['漳州站'],
  '莆田':     ['莆田站'],
  '龙岩':     ['龙岩站'],
  '三明':     ['三明北站'],
  '宁德':     ['宁德站'],
  '南平':     ['南平市站'],
  '武夷山':   ['武夷山东站'],

  // ── 江西省 ──
  '南昌':     ['南昌西站', '南昌站'],
  '景德镇':   ['景德镇北站'],
  '赣州':     ['赣州西站'],
  '上饶':     ['上饶站'],
  '九江':     ['九江站'],
  '宜春':     ['宜春站'],
  '抚州':     ['抚州东站'],
  '新余':     ['新余北站'],
  '萍乡':     ['萍乡北站'],
  '鹰潭':     ['鹰潭北站'],
  '吉安':     ['吉安西站'],

  // ── 山东省 ──
  '济南':     ['济南西站', '济南站'],
  '青岛':     ['青岛北站', '青岛站'],
  '烟台':     ['烟台南站'],
  '威海':     ['威海站'],
  '潍坊':     ['潍坊北站'],
  '临沂':     ['临沂北站'],
  '济宁':     ['济宁北站'],
  '淄博':     ['淄博北站'],
  '枣庄':     ['枣庄站'],
  '泰安':     ['泰安站'],
  '德州':     ['德州东站'],
  '聊城':     ['聊城站'],
  '滨州':     ['滨州站'],
  '菏泽':     ['菏泽东站'],
  '日照':     ['日照西站'],
  '东营':     ['东营南站'],

  // ── 河南省 ──
  '郑州':     ['郑州东站', '郑州站'],
  '洛阳':     ['洛阳龙门站'],
  '南阳':     ['南阳东站'],
  '信阳':     ['信阳东站'],
  '开封':     ['开封北站'],
  '安阳':     ['安阳东站'],
  '新乡':     ['新乡东站'],
  '焦作':     ['焦作站'],
  '许昌':     ['许昌东站'],
  '漯河':     ['漯河西站'],
  '三门峡':   ['三门峡南站'],
  '商丘':     ['商丘站'],
  '周口':     ['周口东站'],
  '驻马店':   ['驻马店西站'],
  '平顶山':   ['平顶山西站'],
  '鹤壁':     ['鹤壁东站'],
  '濮阳':     ['濮阳东站'],

  // ── 湖北省 ──
  '武汉':     ['武汉站', '汉口站'],
  '宜昌':     ['宜昌东站'],
  '襄阳':     ['襄阳东站'],
  '十堰':     ['十堰东站'],
  '荆州':     ['荆州站'],
  '黄冈':     ['黄冈东站'],
  '黄石':     ['黄石北站'],
  '荆门':     ['荆门西站'],
  '孝感':     ['孝感东站'],
  '咸宁':     ['咸宁北站'],
  '恩施':     ['恩施站'],
  '随州':     ['随州南站'],
  '鄂州':     ['鄂州站'],

  // ── 湖南省 ──
  '长沙':     ['长沙南站'],
  '张家界':   ['张家界西站'],
  '衡阳':     ['衡阳东站'],
  '常德':     ['常德站'],
  '怀化':     ['怀化南站'],
  '株洲':     ['株洲西站'],
  '湘潭':     ['湘潭北站'],
  '岳阳':     ['岳阳东站'],
  '邵阳':     ['邵阳北站'],
  '永州':     ['永州站'],
  '益阳':     ['益阳南站'],
  '郴州':     ['郴州西站'],
  '娄底':     ['娄底南站'],

  // ── 广东省 ──
  '广州':     ['广州南站', '广州站'],
  '深圳':     ['深圳北站', '深圳站'],
  '珠海':     ['珠海站'],
  '汕头':     ['潮汕站'],
  '惠州':     ['惠州南站'],
  '湛江':     ['湛江西站'],
  '佛山':     ['佛山西站'],
  '东莞':     ['虎门站'],
  '中山':     ['中山站'],
  '江门':     ['江门站'],
  '肇庆':     ['肇庆东站'],
  '茂名':     ['茂名站'],
  '阳江':     ['阳江站'],
  '韶关':     ['韶关站'],
  '清远':     ['清远站'],
  '梅州':     ['梅州西站'],
  '潮州':     ['潮汕站'],
  '揭阳':     ['潮汕站'],
  '河源':     ['河源东站'],
  '汕尾':     ['汕尾站'],
  '云浮':     ['云浮东站'],

  // ── 广西 ──
  '南宁':     ['南宁东站'],
  '桂林':     ['桂林北站', '桂林站'],
  '北海':     ['北海站'],
  '柳州':     ['柳州站'],
  '百色':     ['百色站'],
  '梧州':     ['梧州南站'],
  '钦州':     ['钦州东站'],
  '玉林':     ['玉林站'],
  '贵港':     ['贵港站'],
  '贺州':     ['贺州站'],
  '来宾':     ['来宾北站'],
  '崇左':     ['崇左南站'],
  '防城港':   ['防城港北站'],

  // ── 海南省 ──
  '海口':     ['海口东站'],
  '三亚':     ['三亚站'],
  '琼海':     ['琼海站'],
  '儋州':     ['儋州站'],
  '万宁':     ['万宁站'],
  '陵水':     ['陵水站'],

  // ── 四川省 ──
  '成都':     ['成都东站', '成都南站'],
  '绵阳':     ['绵阳站'],
  '泸州':     ['泸州站'],
  '宜宾':     ['宜宾西站'],
  '南充':     ['南充北站'],
  '达州':     ['达州站'],
  '乐山':     ['乐山站'],
  '眉山':     ['眉山东站'],
  '德阳':     ['德阳站'],
  '内江':     ['内江北站'],
  '自贡':     ['自贡站'],
  '遂宁':     ['遂宁站'],
  '资阳':     ['资阳北站'],
  '广元':     ['广元站'],

  // ── 贵州省 ──
  '贵阳':     ['贵阳北站', '贵阳东站'],
  '遵义':     ['遵义站'],
  '铜仁':     ['铜仁站'],
  '安顺':     ['安顺西站'],
  '凯里':     ['凯里南站'],
  '都匀':     ['都匀东站'],
  '六盘水':   ['六盘水站'],
  '毕节':     ['毕节站'],
  '兴义':     ['兴义站'],

  // ── 云南省 ──
  '昆明':     ['昆明南站'],
  '大理':     ['大理站'],
  '丽江':     ['丽江站'],
  '曲靖':     ['曲靖北站'],
  '玉溪':     ['玉溪站'],
  '红河':     ['弥勒站'],
  '楚雄':     ['楚雄站'],
  '普洱':     ['普洱站'],
  '西双版纳': ['西双版纳站'],

  // ── 西藏 ──
  // 暂无高铁线路

  // ── 陕西省 ──
  '西安':     ['西安北站'],
  '延安':     ['延安站'],
  '汉中':     ['汉中站'],
  '榆林':     ['榆林站'],
  '宝鸡':     ['宝鸡南站'],
  '咸阳':     ['咸阳秦都站'],
  '渭南':     ['渭南北站'],

  // ── 甘肃省 ──
  '兰州':     ['兰州西站'],
  '天水':     ['天水南站'],
  '嘉峪关':   ['嘉峪关南站'],
  '张掖':     ['张掖西站'],
  '武威':     ['武威南站'],
  '定西':     ['定西北站'],

  // ── 青海省 ──
  '西宁':     ['西宁站'],
  '海东':     ['海东西站'],

  // ── 宁夏 ──
  '银川':     ['银川站'],
  '中卫':     ['中卫南站'],
  '吴忠':     ['吴忠站'],

  // ── 新疆 ──
  '乌鲁木齐': ['乌鲁木齐站'],
  '吐鲁番':   ['吐鲁番北站'],
  '哈密':     ['哈密站'],

  // ── 港澳台 ──
  '香港':     ['香港西九龙站'],
}

/** 查询城市对应高铁站列表 */
export function getTrainStationsByCity(cityName: string): string[] {
  return TRAIN_STATIONS[cityName] ?? []
}
