packages:
  - '.'

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
  - '@img/sharp-darwin-arm64'
  - '@img/sharp-darwin-x64'
  - '@img/sharp-linux-arm64'
  - '@img/sharp-linux-x64'
  - esbuild
  - lightningcss
